### ISSUE TITLE
TypeError: Object of type 'bytes' is not JSON serializable

### ISSUE THREAD

**Issue by mzch** [videntity/vmi#359]
My [Outline]() instance tried to auth by usin VMI, `/o/token/` returned `500` error. Could anyone tell me how to fix this issue?

Python: `3.6.12`
VMI: `commit b55f9cba913a657a2f19db14d1ef10ae8aaff111`
OS: Debian 11.0 (bullseye)

- syslog (`/va/log/daemon.log`)
```
Sep  8 02:11:51 n21 start.sh[2377790]: Internal Server Error: /o/token/
Sep  8 02:11:51 n21 start.sh[2377790]: Traceback (most recent call last):
Sep  8 02:11:51 n21 start.sh[2377790]:   File "/srv/vmi/.pyenv/versions/3.6.12/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
Sep  8 02:11:51 n21 start.sh[2377790]:     response = get_response(request)
Sep  8 02:11:51 n21 start.sh[2377790]:   File "/srv/vmi/.pyenv/versions/3.6.12/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
Sep  8 02:11:51 n21 start.sh[2377790]:     response = self.process_exception_by_middleware(e, request)
Sep  8 02:11:51 n21 start.sh[2377790]:   File "/srv/vmi/.pyenv/versions/3.6.12/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
Sep  8 02:11:51 n21 start.sh[2377790]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Sep  8 02:11:51 n21 start.sh[2377790]:   File "/srv/vmi/.pyenv/versions/3.6.12/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
Sep  8 02:11:51 n21 start.sh[2377790]:     return self.dispatch(request, *args, **kwargs)
Sep  8 02:11:51 n21 start.sh[2377790]:   File "/srv/vmi/.pyenv/versions/3.6.12/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
Sep  8 02:11:51 n21 start.sh[2377790]:     return bound_method(*args, **kwargs)
Sep  8 02:11:51 n21 start.sh[2377790]:   File "/srv/vmi/.pyenv/versions/3.6.12/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
Sep  8 02:11:51 n21 start.sh[2377790]:     return view_func(*args, **kwargs)
Sep  8 02:11:51 n21 start.sh[2377790]:   File "/srv/vmi/.pyenv/versions/3.6.12/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
Sep  8 02:11:51 n21 start.sh[2377790]:     return handler(request, *args, **kwargs)
Sep  8 02:11:51 n21 start.sh[2377790]:   File "/srv/vmi/.pyenv/versions/3.6.12/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
Sep  8 02:11:51 n21 start.sh[2377790]:     return bound_method(*args, **kwargs)
Sep  8 02:11:51 n21 start.sh[2377790]:   File "/srv/vmi/.pyenv/versions/3.6.12/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
Sep  8 02:11:51 n21 start.sh[2377790]:     return view(request, *args, **kwargs)
Sep  8 02:11:51 n21 start.sh[2377790]:   File "/srv/vmi/.pyenv/versions/3.6.12/lib/python3.6/site-packages/oauth2_provider/views/base.py", line 206, in post
Sep  8 02:11:51 n21 start.sh[2377790]:     url, headers, body, status = self.create_token_response(request)
Sep  8 02:11:51 n21 start.sh[2377790]:   File "/srv/vmi/.pyenv/versions/3.6.12/lib/python3.6/site-packages/oauth2_provider/views/mixins.py", line 123, in create_token_response
Sep  8 02:11:51 n21 start.sh[2377790]:     return core.create_token_response(request)
Sep  8 02:11:51 n21 start.sh[2377790]:   File "/srv/vmi/.pyenv/versions/3.6.12/lib/python3.6/site-packages/oauth2_provider/oauth2_backends.py", line 138, in create_token_response
Sep  8 02:11:51 n21 start.sh[2377790]:     headers, extra_credentials)
Sep  8 02:11:51 n21 start.sh[2377790]:   File "/srv/vmi/vmi/src/oauthlib/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
Sep  8 02:11:51 n21 start.sh[2377790]:     return f(endpoint, uri, *args, **kwargs)
Sep  8 02:11:51 n21 start.sh[2377790]:   File "/srv/vmi/vmi/src/oauthlib/oauthlib/oauth2/rfc6749/endpoints/token.py", line 117, in create_token_response
Sep  8 02:11:51 n21 start.sh[2377790]:     request, self.default_token_type)
Sep  8 02:11:51 n21 start.sh[2377790]:   File "/srv/vmi/vmi/src/oauthlib/oauthlib/oauth2/rfc6749/grant_types/authorization_code.py", line 254, in create_token_response
Sep  8 02:11:51 n21 start.sh[2377790]:     return headers, json.dumps(token), 200
Sep  8 02:11:51 n21 start.sh[2377790]:   File "/srv/vmi/.pyenv/versions/3.6.12/lib/python3.6/json/__init__.py", line 231, in dumps
Sep  8 02:11:51 n21 start.sh[2377790]:     return _default_encoder.encode(obj)
Sep  8 02:11:51 n21 start.sh[2377790]:   File "/srv/vmi/.pyenv/versions/3.6.12/lib/python3.6/json/encoder.py", line 199, in encode
Sep  8 02:11:51 n21 start.sh[2377790]:     chunks = self.iterencode(o, _one_shot=True)
Sep  8 02:11:51 n21 start.sh[2377790]:   File "/srv/vmi/.pyenv/versions/3.6.12/lib/python3.6/json/encoder.py", line 257, in iterencode
Sep  8 02:11:51 n21 start.sh[2377790]:     return _iterencode(o, 0)
Sep  8 02:11:51 n21 start.sh[2377790]:   File "/srv/vmi/.pyenv/versions/3.6.12/lib/python3.6/json/encoder.py", line 180, in default
Sep  8 02:11:51 n21 start.sh[2377790]:     o.__class__.__name__)
Sep  8 02:11:51 n21 start.sh[2377790]: TypeError: Object of type 'bytes' is not JSON serializable
```

**Comment by aviars** [comment]
Appears to be some sort of encoding error.  What is Outline?

**Comment by mzch** [comment]
Outline (https://github.com/outline/outline) is a wiki engine. Github URL is also in my first comment.
Is this a problem on their side?

**Comment by mzch** [comment]
I tried [Coral](https://github.com/coralproject/talk), comment engine, and got the same error.
When I use [KeyCloak](https://github.com/keycloak/keycloak), another OIDC provider, I have not got such an error.
I think VMI causes this issue...
